In [ ]:
import pandas as pd
import numpy as np
import os
from utilities.utils import ErrorFunctions
from utilities.diff_reports_v2 import DiffReportUtils

In [17]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
# Define paths
curr_dir = os.getcwd()
misc_dir = os.path.join(curr_dir, 'misc')
sectoral_report_dir = os.path.join(misc_dir, 'sectoral_reports')
dummy_files_dir = os.path.join(misc_dir, 'dummy')
sectoral_report_mapping_dir = os.path.join(misc_dir, 'sectoral_report_mapping')

In [19]:
# Initialize the diff report object
dru = DiffReportUtils('UGA', os.path.join(sectoral_report_mapping_dir, 'sisepuede_edgar_active_crosswalk.csv'), sectoral_report_dir, energy_model_flag=False, comparison_year=2022, sim_init_year=2022)

In [20]:
# Load emissions targets
edgar_emissions = dru.get_edgar_region_df(os.path.join(sectoral_report_mapping_dir, 'emission_targets_uganda.csv'))
edgar_emissions.head()

               ids iso_alpha_3  edgar_emission  year
0  1:lvst-lsmm:ch4         UGA        9.972244  2022
1  1:lvst-lsmm:ch4         UGA        9.972244  2022
2       3:lsmm:n2o         UGA        0.299059  2022
3       4:agrc:co2         UGA        0.000000  2022
4       5:agrc:ch4         UGA        0.576887  2022

In [21]:
edgar_emissions.tail()

              ids iso_alpha_3  edgar_emission  year
58    66:ccsq:ch4         UGA           0.000  2022
59    67:ccsq:co2         UGA           0.000  2022
60    68:ccsq:n2o         UGA           0.000  2022
61  69:frst:total         UGA         -10.524  2022
62  70:lndu:total         UGA          10.611  2022

In [22]:
edgar_emissions.isna().sum()

ids               0
iso_alpha_3       0
edgar_emission    0
year              0
dtype: int64

## Test Diff Report Class Methods

In [23]:
ssp_out = pd.read_csv(os.path.join(dummy_files_dir, 'ssp_uganda_output_dummy.csv'))

In [24]:
ssp_out.head()

,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,area_agrc_crops_other_woody_perennial,area_agrc_crops_pulses,...,yield_agrc_fruits_tonne,yield_agrc_herbs_and_other_perennial_crops_tonne,yield_agrc_nuts_tonne,yield_agrc_other_annual_tonne,yield_agrc_other_woody_perennial_tonne,yield_agrc_pulses_tonne,yield_agrc_rice_tonne,yield_agrc_sugar_cane_tonne,yield_agrc_tubers_tonne,yield_agrc_vegetables_and_vines_tonne
0,0,747901.028486,2.386299e+06,183833.867477,1.333131e+06,595.329750,605228.344795,3.433943e+06,4242.254753,1.090824e+06,...,9.829842e+06,1264.067389,461200.281192,3.374662e+06,1558.604070,855742.438638,371284.928361,8.144525e+06,8.463351e+06,2.839233e+06
1,1,746180.919732,2.380811e+06,183411.065217,1.330065e+06,593.960543,603836.371078,3.426045e+06,4232.497928,1.088315e+06,...,9.589512e+06,1289.597171,432449.975084,3.372849e+06,1555.019391,874816.334236,379914.032975,8.196196e+06,8.657214e+06,2.881371e+06
2,2,745855.348591,2.379772e+06,183331.039920,1.329485e+06,593.701388,603572.907231,3.424550e+06,4230.651219,1.087840e+06,...,9.555432e+06,1268.550416,465394.440892,3.423848e+06,1554.340889,879399.053014,390826.724560,8.171843e+06,9.876628e+06,2.834867e+06
3,3,746831.986263,2.382888e+06,183571.097192,1.331226e+06,594.478792,604363.237474,3.429034e+06,4236.190917,1.089264e+06,...,9.549210e+06,1268.638786,450148.390655,4.942354e+06,1556.376205,876612.253332,398412.478937,8.131891e+06,1.065485e+07,2.843764e+06
4,4,748702.931966,2.388858e+06,184030.975132,1.334561e+06,595.968066,605877.273861,3.437624e+06,4246.803321,1.091993e+06,...,9.634575e+06,1294.481423,277564.514174,5.253808e+06,1560.275189,873391.596641,400599.954899,8.252278e+06,9.158196e+06,2.865777e+06

In [25]:
ssp_edgar_df = dru.load_ssp_edgar_cw()
ssp_edgar_df.tail(20)

,ids,subsector,gas,edgar_class,edgar_subsector,edgar_sector,ignore,note,need_better_information_on_what_is_contained,vars
18,19:trns:co2,trns,co2,EN - Transportation:CO2,EN - Transportation,Energy,NaN,NaN,NaN,emission_co2e_co2_trns_aviation:emission_co2e_...
19,20:trns:ch4,trns,ch4,EN - Transportation:CH4,EN - Transportation,Energy,NaN,NaN,NaN,emission_co2e_ch4_trns_aviation:emission_co2e_...
20,21:trns:n2o,trns,n2o,EN - Transportation:N2O,EN - Transportation,Energy,NaN,NaN,NaN,emission_co2e_n2o_trns_aviation:emission_co2e_...
21,22:ippu:co2,ippu,co2,IN - Industrial Processes:CO2,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_co2_ippu_product_use_product_use...
22,23:ippu:ch4,ippu,ch4,IN - Industrial Processes:CH4,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_ch4_ippu_production_chemicals:em...
23,24:ippu:n2o,ippu,n2o,IN - Industrial Processes:N2O,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_n2o_ippu_production_chemicals:em...
24,50:ippu:hfcs,ippu,hfcs,IN - Industrial Processes:HFC,IN - Industrial Processes,Industrial Processes,NaN,NOTE: can pick this set (HFCs aggregate) or sp...,NaN,emission_co2e_hfcs_ippu_product_use_product_us...
25,51:ippu:other_fcs,ippu,other_fcs,IN - Industrial Processes:HFC,IN - Industrial Processes,Industrial Processes,NaN,NOTE: these aren't HFCs,NaN,NaN
26,52:ippu:pfcs,ippu,pfcs,IN - Industrial Processes:PFC,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_pfcs_ippu_product_use_product_us...
27,53:ippu:sf6,ippu,sf6,IN - Industrial Processes:SF6,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_sf6_ippu_production_chemicals:em...
28,54:waso:co2,waso,co2,Waste - Solid Waste:CO2,Waste - Solid Waste,Waste,NaN,NaN,NaN,emission_co2e_co2_waso_incineration
29,55:waso:ch4,waso,ch4,Waste - Solid Waste:CH4,Waste - Solid Waste,Waste,NaN,NaN,NaN,emission_co2e_ch4_waso_biogas_food:emission_co...
30,56:waso:n2o,waso,n2o,Waste - Solid Waste:N2O,Waste - Solid Waste,Waste,NaN,NaN,NaN,emission_co2e_n2o_waso_compost_food:emission_c...
31,57:trww:ch4,trww,ch4,Waste - Wastewater Treatment:CH4,Waste - Wastewater Treatment,Waste,NaN,NaN,NaN,emission_co2e_ch4_trww_treated_advanced_aerobi...
32,58:trww:n2o,trww,n2o,Waste - Wastewater Treatment:N2O,Waste - Wastewater Treatment,Waste,NaN,NaN,NaN,emission_co2e_n2o_trww_treated_advanced_aerobi...
33,66:ccsq:ch4,ccsq,ch4,CCSQ:CH4,CCSQ,CCSQ,NaN,NaN,NaN,emission_co2e_ch4_ccsq_direct_air_capture
34,67:ccsq:co2,ccsq,co2,CCSQ:CO2,CCSQ,CCSQ,NaN,NaN,NaN,emission_co2e_co2_ccsq_direct_air_capture
35,68:ccsq:n2o,ccsq,n2o,CCSQ:N2O,CCSQ,CCSQ,NaN,NaN,NaN,emission_co2e_n2o_ccsq_direct_air_capture
36,69:frst:total,frst,NaN,NaN,NaN,"Land Use, Land Use Change, and Forestry",NaN,NaN,NaN,emission_co2e_co2_frst_sequestration_mangroves...
37,70:lndu:total,lndu,NaN,NaN,NaN,"Land Use, Land Use Change, and Forestry",NaN,NaN,NaN,emission_co2e_co2_lndu_conversion_away_croplan...

In [26]:
# ssp_edgar_df[ssp_edgar_df.ignore == 1]

In [27]:
ssp_emissions_report, model_failed_flag = dru.generate_ssp_emissions_report(ssp_out, debug=True)
ssp_emissions_report

Missing variables for entc True
Variables: ['emission_co2e_co2_entc_generation_pp_biogas', 'emission_co2e_co2_entc_generation_pp_biomass', 'emission_co2e_co2_entc_generation_pp_coal', 'emission_co2e_co2_entc_generation_pp_coal_ccs', 'emission_co2e_co2_entc_generation_pp_gas', 'emission_co2e_co2_entc_generation_pp_gas_ccs', 'emission_co2e_co2_entc_generation_pp_geothermal', 'emission_co2e_co2_entc_generation_pp_hydropower', 'emission_co2e_co2_entc_generation_pp_nuclear', 'emission_co2e_co2_entc_generation_pp_ocean', 'emission_co2e_co2_entc_generation_pp_oil', 'emission_co2e_co2_entc_generation_pp_solar', 'emission_co2e_co2_entc_generation_pp_waste_incineration', 'emission_co2e_co2_entc_generation_pp_wind']
Missing variables for entc True
Variables: ['emission_co2e_ch4_entc_generation_pp_biogas', 'emission_co2e_ch4_entc_generation_pp_biomass', 'emission_co2e_ch4_entc_generation_pp_coal', 'emission_co2e_ch4_entc_generation_pp_coal_ccs', 'emission_co2e_ch4_entc_generation_pp_gas', 'emission_co2e_ch4_entc_generation_pp_gas_ccs', 'emission_co2e_ch4_entc_generation_pp_geothermal', 'emission_co2e_ch4_entc_generation_pp_hydropower', 'emission_co2e_ch4_entc_generation_pp_nuclear', 'emission_co2e_ch4_entc_generation_pp_ocean', 'emission_co2e_ch4_entc_generation_pp_oil', 'emission_co2e_ch4_entc_generation_pp_solar', 'emission_co2e_ch4_entc_generation_pp_waste_incineration', 'emission_co2e_ch4_entc_generation_pp_wind']
Missing variables for entc True
Variables: ['emission_co2e_n2o_entc_generation_pp_biogas', 'emission_co2e_n2o_entc_generation_pp_biomass', 'emission_co2e_n2o_entc_generation_pp_coal', 'emission_co2e_n2o_entc_generation_pp_coal_ccs', 'emission_co2e_n2o_entc_generation_pp_gas', 'emission_co2e_n2o_entc_generation_pp_gas_ccs', 'emission_co2e_n2o_entc_generation_pp_geothermal', 'emission_co2e_n2o_entc_generation_pp_hydropower', 'emission_co2e_n2o_entc_generation_pp_nuclear', 'emission_co2e_n2o_entc_generation_pp_ocean', 'emission_co2e_n2o_entc_generation_pp_oil', 'emission_co2e_n2o_entc_generation_pp_solar', 'emission_co2e_n2o_entc_generation_pp_waste_incineration', 'emission_co2e_n2o_entc_generation_pp_wind']
Missing variables for fgtv True
Variables: ['emission_co2e_co2_fgtv_fuel_coal', 'emission_co2e_co2_fgtv_fuel_natural_gas', 'emission_co2e_co2_fgtv_fuel_oil', 'emission_co2e_co2_entc_fuel_mining_and_extraction_me_coal', 'emission_co2e_co2_entc_fuel_mining_and_extraction_me_crude', 'emission_co2e_co2_entc_fuel_mining_and_extraction_me_natural_gas', 'emission_co2e_co2_entc_processing_and_refinement_fp_ammonia_production', 'emission_co2e_co2_entc_processing_and_refinement_fp_hydrogen_electrolysis', 'emission_co2e_co2_entc_processing_and_refinement_fp_hydrogen_gasification', 'emission_co2e_co2_entc_processing_and_refinement_fp_hydrogen_reformation', 'emission_co2e_co2_entc_processing_and_refinement_fp_hydrogen_reformation_ccs', 'emission_co2e_co2_entc_processing_and_refinement_fp_natural_gas', 'emission_co2e_co2_entc_processing_and_refinement_fp_petroleum_refinement']
Missing variables for fgtv True
Variables: ['emission_co2e_ch4_fgtv_fuel_coal', 'emission_co2e_ch4_fgtv_fuel_natural_gas', 'emission_co2e_ch4_fgtv_fuel_oil', 'emission_co2e_ch4_entc_fuel_mining_and_extraction_me_coal', 'emission_co2e_ch4_entc_fuel_mining_and_extraction_me_crude', 'emission_co2e_ch4_entc_fuel_mining_and_extraction_me_natural_gas', 'emission_co2e_ch4_entc_processing_and_refinement_fp_ammonia_production', 'emission_co2e_ch4_entc_processing_and_refinement_fp_hydrogen_electrolysis', 'emission_co2e_ch4_entc_processing_and_refinement_fp_hydrogen_gasification', 'emission_co2e_ch4_entc_processing_and_refinement_fp_hydrogen_reformation', 'emission_co2e_ch4_entc_processing_and_refinement_fp_hydrogen_reformation_ccs', 'emission_co2e_ch4_entc_processing_and_refinement_fp_natural_gas', 'emission_co2e_ch4_entc_processing_and_refinement_fp_petroleum_refinement']
Missing variables for fgtv True
Variables: ['emission_co2e_n2o_fgtv_fuel_coal', 'emission_co2e_n2o_fgtv_fuel_natural_gas', 'emission_co2e_n2o_fgtv_fuel_oil', 'emission_co2e_n2o_entc_fuel_mining_and_extraction_me_coal', 'emission_co2e_n2o_entc_fuel_mining_and_extraction_me_crude', 'emission_co2e_n2o_entc_fuel_mining_and_extraction_me_natural_gas', 'emission_co2e_n2o_entc_processing_and_refinement_fp_ammonia_production', 'emission_co2e_n2o_entc_processing_and_refinement_fp_hydrogen_electrolysis', 'emission_co2e_n2o_entc_processing_and_refinement_fp_hydrogen_gasification', 'emission_co2e_n2o_entc_processing_and_refinement_fp_hydrogen_reformation', 'emission_co2e_n2o_entc_processing_and_refinement_fp_hydrogen_reformation_ccs', 'emission_co2e_n2o_entc_processing_and_refinement_fp_natural_gas', 'emission_co2e_n2o_entc_processing_and_refinement_fp_petroleum_refinement']

                  ids subsector  ssp_emission
0     1:lvst-lsmm:ch4      lvst     59.862185
1     1:lvst-lsmm:ch4      lsmm      2.511765
2          3:lsmm:n2o      lsmm      6.355724
3          4:agrc:co2      agrc      0.472549
4          5:agrc:ch4      agrc      0.640436
5          6:agrc:n2o      agrc      0.951436
6          7:scoe:co2      scoe      0.000000
7          8:scoe:ch4      scoe      0.000000
8          9:scoe:n2o      scoe      0.000000
9         10:entc:co2      entc           NaN
10        11:entc:ch4      entc           NaN
11        12:entc:n2o      entc           NaN
12        13:fgtv:co2      fgtv           NaN
13        14:fgtv:ch4      fgtv           NaN
14        15:fgtv:n2o      fgtv           NaN
15        16:inen:co2      inen     29.992048
16        17:inen:ch4      inen      0.122654
17        18:inen:n2o      inen      0.216827
18        19:trns:co2      trns      5.291926
19        20:trns:ch4      trns      0.013409
20        21:trns:n2o      trns      0.083667
21        22:ippu:co2      ippu      1.954773
22        23:ippu:ch4      ippu      0.006587
23        24:ippu:n2o      ippu      0.541484
24       50:ippu:hfcs      ippu      0.000000
25  51:ippu:other_fcs      ippu           NaN
26       52:ippu:pfcs      ippu      0.000002
27        53:ippu:sf6      ippu      0.000000
28        54:waso:co2      waso      0.917384
29        55:waso:ch4      waso      6.691055
30        56:waso:n2o      waso      0.009488
31        57:trww:ch4      trww      3.811485
32        58:trww:n2o      trww      2.606634
33        66:ccsq:ch4      ccsq      0.000000
34        67:ccsq:co2      ccsq      0.000000
35        68:ccsq:n2o      ccsq      0.000000
36      69:frst:total      frst    -10.628637
37      70:lndu:total      lndu     16.915971

In [29]:
ssp_emissions_report = dru.group_ssp_emissions_report_vars(ssp_emissions_report)
ssp_emissions_report

                  ids  ssp_emission subsector
0         10:entc:co2      0.000000      entc
1         11:entc:ch4      0.000000      entc
2         12:entc:n2o      0.000000      entc
3         13:fgtv:co2      0.000000      fgtv
4         14:fgtv:ch4      0.000000      fgtv
5         15:fgtv:n2o      0.000000      fgtv
6         16:inen:co2     29.992048      inen
7         17:inen:ch4      0.122654      inen
8         18:inen:n2o      0.216827      inen
9         19:trns:co2      5.291926      trns
10    1:lvst-lsmm:ch4     62.373950      lvst
11        20:trns:ch4      0.013409      trns
12        21:trns:n2o      0.083667      trns
13        22:ippu:co2      1.954773      ippu
14        23:ippu:ch4      0.006587      ippu
15        24:ippu:n2o      0.541484      ippu
16         3:lsmm:n2o      6.355724      lsmm
17         4:agrc:co2      0.472549      agrc
18       50:ippu:hfcs      0.000000      ippu
19  51:ippu:other_fcs      0.000000      ippu
20       52:ippu:pfcs      0.000002      ippu
21        53:ippu:sf6      0.000000      ippu
22        54:waso:co2      0.917384      waso
23        55:waso:ch4      6.691055      waso
24        56:waso:n2o      0.009488      waso
25        57:trww:ch4      3.811485      trww
26        58:trww:n2o      2.606634      trww
27         5:agrc:ch4      0.640436      agrc
28        66:ccsq:ch4      0.000000      ccsq
29        67:ccsq:co2      0.000000      ccsq
30        68:ccsq:n2o      0.000000      ccsq
31      69:frst:total    -10.628637      frst
32         6:agrc:n2o      0.951436      agrc
33      70:lndu:total     16.915971      lndu
34         7:scoe:co2      0.000000      scoe
35         8:scoe:ch4      0.000000      scoe
36         9:scoe:n2o      0.000000      scoe

In [30]:
# check energy subsector
energy_subsectors = ['trns', 'entc', 'fgtv', 'scoe', 'inen', 'ccsq']
ssp_emissions_report[ssp_emissions_report.subsector.isin(energy_subsectors)]

            ids  ssp_emission subsector
0   10:entc:co2      0.000000      entc
1   11:entc:ch4      0.000000      entc
2   12:entc:n2o      0.000000      entc
3   13:fgtv:co2      0.000000      fgtv
4   14:fgtv:ch4      0.000000      fgtv
5   15:fgtv:n2o      0.000000      fgtv
6   16:inen:co2     29.992048      inen
7   17:inen:ch4      0.122654      inen
8   18:inen:n2o      0.216827      inen
9   19:trns:co2      5.291926      trns
11  20:trns:ch4      0.013409      trns
12  21:trns:n2o      0.083667      trns
28  66:ccsq:ch4      0.000000      ccsq
29  67:ccsq:co2      0.000000      ccsq
30  68:ccsq:n2o      0.000000      ccsq
34   7:scoe:co2      0.000000      scoe
35   8:scoe:ch4      0.000000      scoe
36   9:scoe:n2o      0.000000      scoe

In [31]:
model_failed_flag

False

In [32]:
edgar_emissions_groupped = dru.group_ssp_emissions_report_vars(edgar_emissions, emissions_col_name="edgar_emission")
edgar_emissions_groupped["iso_alpha_3"] = dru.iso_alpha_3
edgar_emissions_groupped

              ids  edgar_emission iso_alpha_3
0     10:entc:co2        0.056306         UGA
1     11:entc:ch4        0.003233         UGA
2     12:entc:n2o        0.004118         UGA
3     13:fgtv:co2        0.000000         UGA
4     14:fgtv:ch4        7.845444         UGA
..            ...             ...         ...
57     6:agrc:n2o        8.092843         UGA
58  70:lndu:total       10.611000         UGA
59     7:scoe:co2        0.611469         UGA
60     8:scoe:ch4        2.554441         UGA
61     9:scoe:n2o        0.323356         UGA

[62 rows x 3 columns]

In [33]:
df_report = dru.merge_ssp_with_edgar(ssp_emissions_report, edgar_emissions_groupped)
df_report

,ids,ssp_emission,subsector,edgar_emission,iso_alpha_3,year
0,10:entc:co2,0.000000,entc,0.056306,UGA,2022
1,11:entc:ch4,0.000000,entc,0.003233,UGA,2022
2,12:entc:n2o,0.000000,entc,0.004118,UGA,2022
3,13:fgtv:co2,0.000000,fgtv,0.000000,UGA,2022
4,14:fgtv:ch4,0.000000,fgtv,7.845444,UGA,2022
5,15:fgtv:n2o,0.000000,fgtv,0.093892,UGA,2022
6,16:inen:co2,29.992048,inen,1.282418,UGA,2022
7,17:inen:ch4,0.122654,inen,0.223206,UGA,2022
8,18:inen:n2o,0.216827,inen,0.157472,UGA,2022
9,19:trns:co2,5.291926,trns,3.824464,UGA,2022
10,1:lvst-lsmm:ch4,62.373950,lvst,19.944488,UGA,2022
11,20:trns:ch4,0.013409,trns,0.025259,UGA,2022
12,21:trns:n2o,0.083667,trns,0.053780,UGA,2022
13,22:ippu:co2,1.954773,ippu,1.765612,UGA,2022
14,23:ippu:ch4,0.006587,ippu,0.000000,UGA,2022
15,24:ippu:n2o,0.541484,ippu,0.534607,UGA,2022
16,3:lsmm:n2o,6.355724,lsmm,0.299059,UGA,2022
17,4:agrc:co2,0.472549,agrc,0.000000,UGA,2022
18,50:ippu:hfcs,0.000000,ippu,0.000000,UGA,2022
19,51:ippu:other_fcs,0.000000,ippu,0.000000,UGA,2022
20,52:ippu:pfcs,0.000002,ippu,0.000000,UGA,2022
21,53:ippu:sf6,0.000000,ippu,0.000000,UGA,2022
22,54:waso:co2,0.917384,waso,0.000000,UGA,2022
23,55:waso:ch4,6.691055,waso,0.595829,UGA,2022
24,56:waso:n2o,0.009488,waso,0.000000,UGA,2022
25,57:trww:ch4,3.811485,trww,7.170170,UGA,2022
26,58:trww:n2o,2.606634,trww,0.452025,UGA,2022
27,5:agrc:ch4,0.640436,agrc,0.576887,UGA,2022
28,66:ccsq:ch4,0.000000,ccsq,0.000000,UGA,2022
29,67:ccsq:co2,0.000000,ccsq,0.000000,UGA,2022
30,68:ccsq:n2o,0.000000,ccsq,0.000000,UGA,2022
31,69:frst:total,-10.628637,frst,-10.524000,UGA,2022
32,6:agrc:n2o,0.951436,agrc,8.092843,UGA,2022
33,70:lndu:total,16.915971,lndu,10.611000,UGA,2022
34,7:scoe:co2,0.000000,scoe,0.611469,UGA,2022
35,8:scoe:ch4,0.000000,scoe,2.554441,UGA,2022
36,9:scoe:n2o,0.000000,scoe,0.323356,UGA,2022

In [34]:
dru.group_trns_scoe_inen(df_report)

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year
0,16:inen:co2,inen,30.331529,UGA,1.663096,2022
1,7:scoe:co2,scoe,0.000000,UGA,3.489266,2022
2,19:trns:co2,trns,5.389002,UGA,3.903503,2022
3,10:entc:co2,entc,0.000000,UGA,0.056306,2022
4,11:entc:ch4,entc,0.000000,UGA,0.003233,2022
5,12:entc:n2o,entc,0.000000,UGA,0.004118,2022
6,13:fgtv:co2,fgtv,0.000000,UGA,0.000000,2022
7,14:fgtv:ch4,fgtv,0.000000,UGA,7.845444,2022
8,15:fgtv:n2o,fgtv,0.000000,UGA,0.093892,2022
9,1:lvst-lsmm:ch4,lvst,62.373950,UGA,19.944488,2022
10,22:ippu:co2,ippu,1.954773,UGA,1.765612,2022
11,23:ippu:ch4,ippu,0.006587,UGA,0.000000,2022
12,24:ippu:n2o,ippu,0.541484,UGA,0.534607,2022
13,3:lsmm:n2o,lsmm,6.355724,UGA,0.299059,2022
14,4:agrc:co2,agrc,0.472549,UGA,0.000000,2022
15,50:ippu:hfcs,ippu,0.000000,UGA,0.000000,2022
16,51:ippu:other_fcs,ippu,0.000000,UGA,0.000000,2022
17,52:ippu:pfcs,ippu,0.000002,UGA,0.000000,2022
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022
19,54:waso:co2,waso,0.917384,UGA,0.000000,2022
20,55:waso:ch4,waso,6.691055,UGA,0.595829,2022
21,56:waso:n2o,waso,0.009488,UGA,0.000000,2022
22,57:trww:ch4,trww,3.811485,UGA,7.170170,2022
23,58:trww:n2o,trww,2.606634,UGA,0.452025,2022
24,5:agrc:ch4,agrc,0.640436,UGA,0.576887,2022
25,66:ccsq:ch4,ccsq,0.000000,UGA,0.000000,2022
26,67:ccsq:co2,ccsq,0.000000,UGA,0.000000,2022
27,68:ccsq:n2o,ccsq,0.000000,UGA,0.000000,2022
28,69:frst:total,frst,-10.628637,UGA,-10.524000,2022
29,6:agrc:n2o,agrc,0.951436,UGA,8.092843,2022
30,70:lndu:total,lndu,16.915971,UGA,10.611000,2022

In [35]:
# get duplicated edgar_class
df_report[df_report.duplicated(subset=['ids'], keep=False)]

Empty DataFrame
Columns: [ids, ssp_emission, subsector, edgar_emission, iso_alpha_3, year]
Index: []

In [36]:

reports_dict = dru.run_report_generator(edgar_emissions, ssp_out)

sectoral_emission_report = reports_dict['sectoral_emission_report']
subsector_emission_report = reports_dict['subsector_emission_report']

In [37]:
sectoral_emission_report[sectoral_emission_report['subsector'].isin(energy_subsectors)]

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
0,16:inen:co2,inen,30.331529,UGA,1.663096,2022,1.663097,17.237980,821.879005,1.663097,0.023887,0.979489
1,7:scoe:co2,scoe,0.000000,UGA,3.489266,2022,3.489267,-1.000000,12.174987,3.489267,0.050117,1.501689
2,19:trns:co2,trns,5.389002,UGA,3.903503,2022,3.903504,0.380555,2.206701,3.903504,0.056067,1.589950

In [38]:
sectoral_emission_report

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
0,16:inen:co2,inen,30.331529,UGA,1.663096,2022,1.663097,17.237980,8.218790e+02,1.663097,0.023887,0.979489
1,7:scoe:co2,scoe,0.000000,UGA,3.489266,2022,3.489267,-1.000000,1.217499e+01,3.489267,0.050117,1.501689
2,19:trns:co2,trns,5.389002,UGA,3.903503,2022,3.903504,0.380555,2.206701e+00,3.903504,0.056067,1.589950
9,1:lvst-lsmm:ch4,lvst,62.373950,UGA,19.944488,2022,19.944489,2.127378,1.800259e+03,19.944489,0.286467,3.041876
10,22:ippu:co2,ippu,1.954773,UGA,1.765612,2022,1.765613,0.107136,3.578159e-02,1.765613,0.025360,1.017262
11,23:ippu:ch4,ippu,0.006587,UGA,0.000000,2022,0.000001,6586.248325,4.337867e-05,0.000001,0.000000,0.000000
12,24:ippu:n2o,ippu,0.541484,UGA,0.534607,2022,0.534608,0.012862,4.728029e-05,0.534608,0.007679,0.428275
13,3:lsmm:n2o,lsmm,6.355724,UGA,0.299059,2022,0.299060,20.252354,3.668318e+01,0.299060,0.004295,0.261640
14,4:agrc:co2,agrc,0.472549,UGA,0.000000,2022,0.000001,472548.279207,2.233019e-01,0.000001,0.000000,0.000000
15,50:ippu:hfcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
16,51:ippu:other_fcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
17,52:ippu:pfcs,ippu,0.000002,UGA,0.000000,2022,0.000001,1.366543,1.867440e-12,0.000001,0.000000,0.000000
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
19,54:waso:co2,waso,0.917384,UGA,0.000000,2022,0.000001,917382.878774,8.415913e-01,0.000001,0.000000,0.000000
20,55:waso:ch4,waso,6.691055,UGA,0.595829,2022,0.595830,10.229810,3.715177e+01,0.595830,0.008558,0.467393
21,56:waso:n2o,waso,0.009488,UGA,0.000000,2022,0.000001,9487.130033,9.000564e-05,0.000001,0.000000,0.000000
22,57:trww:ch4,trww,3.811485,UGA,7.170170,2022,7.170171,-0.468425,1.128077e+01,7.170171,0.102987,2.100490
23,58:trww:n2o,trww,2.606634,UGA,0.452025,2022,0.452026,4.766564,4.642339e+00,0.452026,0.006493,0.372959
24,5:agrc:ch4,agrc,0.640436,UGA,0.576887,2022,0.576888,0.110157,4.038345e-03,0.576888,0.008286,0.455452
28,69:frst:total,frst,-10.628637,UGA,-10.524000,2022,-10.523999,0.009943,1.094908e-02,10.524001,0.151158,2.444432
29,6:agrc:n2o,agrc,0.951436,UGA,8.092843,2022,8.092844,-0.882435,5.099971e+01,8.092844,0.116239,2.207488
30,70:lndu:total,lndu,16.915971,UGA,10.611000,2022,10.611001,0.594192,3.975265e+01,10.611001,0.152408,2.451953

In [39]:
sectoral_emission_report.tail(10)

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
19,54:waso:co2,waso,0.917384,UGA,0.000000,2022,0.000001,917382.878774,8.415913e-01,0.000001,0.000000,0.000000
20,55:waso:ch4,waso,6.691055,UGA,0.595829,2022,0.595830,10.229810,3.715177e+01,0.595830,0.008558,0.467393
21,56:waso:n2o,waso,0.009488,UGA,0.000000,2022,0.000001,9487.130033,9.000564e-05,0.000001,0.000000,0.000000
22,57:trww:ch4,trww,3.811485,UGA,7.170170,2022,7.170171,-0.468425,1.128077e+01,7.170171,0.102987,2.100490
23,58:trww:n2o,trww,2.606634,UGA,0.452025,2022,0.452026,4.766564,4.642339e+00,0.452026,0.006493,0.372959
24,5:agrc:ch4,agrc,0.640436,UGA,0.576887,2022,0.576888,0.110157,4.038345e-03,0.576888,0.008286,0.455452
28,69:frst:total,frst,-10.628637,UGA,-10.524000,2022,-10.523999,0.009943,1.094908e-02,10.524001,0.151158,2.444432
29,6:agrc:n2o,agrc,0.951436,UGA,8.092843,2022,8.092844,-0.882435,5.099971e+01,8.092844,0.116239,2.207488
30,70:lndu:total,lndu,16.915971,UGA,10.611000,2022,10.611001,0.594192,3.975265e+01,10.611001,0.152408,2.451953

In [40]:
sectoral_emission_report[sectoral_emission_report['subsector'] == 'ippu']

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
10,22:ippu:co2,ippu,1.954773,UGA,1.765612,2022,1.765613,0.107136,3.578159e-02,1.765613,0.025360,1.017262
11,23:ippu:ch4,ippu,0.006587,UGA,0.000000,2022,0.000001,6586.248325,4.337867e-05,0.000001,0.000000,0.000000
12,24:ippu:n2o,ippu,0.541484,UGA,0.534607,2022,0.534608,0.012862,4.728029e-05,0.534608,0.007679,0.428275
15,50:ippu:hfcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
16,51:ippu:other_fcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
17,52:ippu:pfcs,ippu,0.000002,UGA,0.000000,2022,0.000001,1.366543,1.867440e-12,0.000001,0.000000,0.000000
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000

In [41]:
subsector_emission_report

,subsector,ssp_emission,edgar_emission_epsilon,rel_error,squared_diff,year
0,agrc,2.064421,8.669733,-0.761882,43.630147,2022
1,frst,-10.628637,-10.523999,0.009943,0.010949,2022
2,inen,30.331529,1.663097,17.237980,821.879005,2022
3,ippu,2.502847,2.300226,0.088087,0.041055,2022
4,lndu,16.915971,10.611001,0.594192,39.752651,2022
5,lsmm,6.355724,0.299060,20.252354,36.683184,2022
6,lvst,62.373950,19.944489,2.127378,1800.259200,2022
7,scoe,NaN,3.489267,NaN,NaN,2022
8,trns,5.389002,3.903504,0.380555,2.206701,2022
9,trww,6.418119,7.622196,-0.157970,1.449800,2022
10,waso,7.617927,0.595832,11.785366,49.309821,2022

### Test new error function

In [ ]:
input_df = pd.read_csv('misc/dummy/ssp_output_dummy.csv')
input_df.head()

In [ ]:
dru.run_report_generator(edgar_emissions, input_df)

In [ ]:
df = dru.sectoral_emission_report.copy()
df.head()

In [ ]:
df.to_csv('misc/dummy/sectoral_emission_report_dummy.csv', index=False)

In [ ]:
df.sort_values(by=['norm_weight'], ascending=False, inplace=True)

In [ ]:
df

In [ ]:
df['norm_weight'] * 100

In [ ]:
ef = ErrorFunctions()
ef.calculate_error(error_type='wmape', dataframe=df)

In [ ]:
np.sum(df['norm_weight'] * df['rel_error'].abs()) * 100