In [19]:
import pandas as pd
import numpy as np
import os
from utilities.utils import ErrorFunctions, SSPModelForCalibration
from utilities.diff_reports_v2 import DiffReportUtils

In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [21]:
# Define paths
curr_dir = os.getcwd()
misc_dir = os.path.join(curr_dir, 'misc')
sectoral_report_dir = os.path.join(misc_dir, 'sectoral_reports')
dummy_files_dir = os.path.join(misc_dir, 'dummy')
sectoral_report_mapping_dir = os.path.join(misc_dir, 'sectoral_report_mapping')

In [22]:
# Initialize the diff report object
dru = DiffReportUtils('UGA', os.path.join(sectoral_report_mapping_dir, 'sisepuede_edgar_active_crosswalk.csv'), sectoral_report_dir, energy_model_flag=False, comparison_year=2022, sim_init_year=2022)

In [23]:
# Load emissions targets
edgar_emissions = dru.get_edgar_region_df(os.path.join(sectoral_report_mapping_dir, 'emission_targets_uganda.csv'))
edgar_emissions.head()

               ids iso_alpha_3  edgar_emission  year
0  1:lvst-lsmm:ch4         UGA        9.972244  2022
1  1:lvst-lsmm:ch4         UGA        9.972244  2022
2       3:lsmm:n2o         UGA        0.299059  2022
3       4:agrc:co2         UGA        0.000000  2022
4       5:agrc:ch4         UGA        0.576887  2022

In [24]:
edgar_emissions.tail()

              ids iso_alpha_3  edgar_emission  year
58    66:ccsq:ch4         UGA           0.000  2022
59    67:ccsq:co2         UGA           0.000  2022
60    68:ccsq:n2o         UGA           0.000  2022
61  69:frst:total         UGA         -10.524  2022
62  70:lndu:total         UGA          10.611  2022

In [25]:
edgar_emissions.isna().sum()

ids               0
iso_alpha_3       0
edgar_emission    0
year              0
dtype: int64

## Test Diff Report Class Methods

In [26]:
ssp_out = pd.read_csv(os.path.join(dummy_files_dir, 'ssp_uganda_output_dummy.csv'))

In [27]:
ssp_out.head()

,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,area_agrc_crops_other_woody_perennial,area_agrc_crops_pulses,...,yield_agrc_fruits_tonne,yield_agrc_herbs_and_other_perennial_crops_tonne,yield_agrc_nuts_tonne,yield_agrc_other_annual_tonne,yield_agrc_other_woody_perennial_tonne,yield_agrc_pulses_tonne,yield_agrc_rice_tonne,yield_agrc_sugar_cane_tonne,yield_agrc_tubers_tonne,yield_agrc_vegetables_and_vines_tonne
0,0,1.110674e+06,2.470537e+06,512618.657191,1.336131e+06,1.724155e+06,940987.489485,1.244761e+06,830632.082001,571949.517471,...,9.851960e+06,3.660909e+06,717057.782374,1.223273e+06,305174.162968,448689.809992,1.088927e+06,5.904929e+07,2.194701e+06,1.187277e+06
1,1,1.099568e+06,2.445834e+06,507493.032449,1.322771e+06,1.706915e+06,931578.645912,1.232315e+06,822326.671554,566230.649153,...,9.536923e+06,3.706026e+06,667169.430627,1.213181e+06,302122.755810,455151.199769,1.105636e+06,5.896535e+07,2.227650e+06,1.195600e+06
2,2,1.108967e+06,2.466741e+06,511831.054023,1.334078e+06,1.721506e+06,939541.727186,1.242849e+06,829355.873165,571070.756532,...,9.588445e+06,3.678309e+06,724448.535785,1.242594e+06,304705.283940,461647.924279,1.147618e+06,5.931858e+07,2.564269e+06,1.186876e+06
3,3,1.097881e+06,2.442080e+06,506714.112877,1.320741e+06,1.704295e+06,930148.823640,1.230424e+06,821064.533360,565361.576856,...,9.473999e+06,3.637027e+06,692803.554751,1.773441e+06,301659.046334,454988.571853,1.156682e+06,5.836201e+07,2.735081e+06,1.177157e+06
4,4,1.107827e+06,2.464205e+06,511304.810668,1.332707e+06,1.719736e+06,938575.729546,1.241571e+06,828503.164027,570483.605385,...,9.621189e+06,3.735378e+06,429980.347008,1.897525e+06,304391.998669,456280.825701,1.170637e+06,5.961326e+07,2.366263e+06,1.194025e+06

In [28]:
ssp_edgar_df = dru.load_ssp_edgar_cw()
ssp_edgar_df.tail(20)

,ids,subsector,gas,edgar_class,edgar_subsector,edgar_sector,ignore,note,need_better_information_on_what_is_contained,vars
18,19:trns:co2,trns,co2,EN - Transportation:CO2,EN - Transportation,Energy,NaN,NaN,NaN,emission_co2e_co2_trns_aviation:emission_co2e_...
19,20:trns:ch4,trns,ch4,EN - Transportation:CH4,EN - Transportation,Energy,NaN,NaN,NaN,emission_co2e_ch4_trns_aviation:emission_co2e_...
20,21:trns:n2o,trns,n2o,EN - Transportation:N2O,EN - Transportation,Energy,NaN,NaN,NaN,emission_co2e_n2o_trns_aviation:emission_co2e_...
21,22:ippu:co2,ippu,co2,IN - Industrial Processes:CO2,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_co2_ippu_product_use_product_use...
22,23:ippu:ch4,ippu,ch4,IN - Industrial Processes:CH4,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_ch4_ippu_production_chemicals:em...
23,24:ippu:n2o,ippu,n2o,IN - Industrial Processes:N2O,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_n2o_ippu_production_chemicals:em...
24,50:ippu:hfcs,ippu,hfcs,IN - Industrial Processes:HFC,IN - Industrial Processes,Industrial Processes,NaN,NOTE: can pick this set (HFCs aggregate) or sp...,NaN,emission_co2e_hfcs_ippu_product_use_product_us...
25,51:ippu:other_fcs,ippu,other_fcs,IN - Industrial Processes:HFC,IN - Industrial Processes,Industrial Processes,NaN,NOTE: these aren't HFCs,NaN,NaN
26,52:ippu:pfcs,ippu,pfcs,IN - Industrial Processes:PFC,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_pfcs_ippu_product_use_product_us...
27,53:ippu:sf6,ippu,sf6,IN - Industrial Processes:SF6,IN - Industrial Processes,Industrial Processes,NaN,NaN,NaN,emission_co2e_sf6_ippu_production_chemicals:em...
28,54:waso:co2,waso,co2,Waste - Solid Waste:CO2,Waste - Solid Waste,Waste,NaN,NaN,NaN,emission_co2e_co2_waso_incineration
29,55:waso:ch4,waso,ch4,Waste - Solid Waste:CH4,Waste - Solid Waste,Waste,NaN,NaN,NaN,emission_co2e_ch4_waso_biogas_food:emission_co...
30,56:waso:n2o,waso,n2o,Waste - Solid Waste:N2O,Waste - Solid Waste,Waste,NaN,NaN,NaN,emission_co2e_n2o_waso_compost_food:emission_c...
31,57:trww:ch4,trww,ch4,Waste - Wastewater Treatment:CH4,Waste - Wastewater Treatment,Waste,NaN,NaN,NaN,emission_co2e_ch4_trww_treated_advanced_aerobi...
32,58:trww:n2o,trww,n2o,Waste - Wastewater Treatment:N2O,Waste - Wastewater Treatment,Waste,NaN,NaN,NaN,emission_co2e_n2o_trww_treated_advanced_aerobi...
33,66:ccsq:ch4,ccsq,ch4,CCSQ:CH4,CCSQ,CCSQ,NaN,NaN,NaN,emission_co2e_ch4_ccsq_direct_air_capture
34,67:ccsq:co2,ccsq,co2,CCSQ:CO2,CCSQ,CCSQ,NaN,NaN,NaN,emission_co2e_co2_ccsq_direct_air_capture
35,68:ccsq:n2o,ccsq,n2o,CCSQ:N2O,CCSQ,CCSQ,NaN,NaN,NaN,emission_co2e_n2o_ccsq_direct_air_capture
36,69:frst:total,frst,NaN,NaN,NaN,"Land Use, Land Use Change, and Forestry",NaN,NaN,NaN,emission_co2e_co2_frst_sequestration_mangroves...
37,70:lndu:total,lndu,NaN,NaN,NaN,"Land Use, Land Use Change, and Forestry",NaN,NaN,NaN,emission_co2e_co2_lndu_conversion_away_croplan...

In [29]:
# ssp_edgar_df[ssp_edgar_df.ignore == 1]

In [30]:
ssp_emissions_report, model_failed_flag = dru.generate_ssp_emissions_report(ssp_out, debug=True)
ssp_emissions_report

Missing variables for entc True
Missing variables for entc True
Missing variables for entc True
Missing variables for fgtv True
Missing variables for fgtv True
Missing variables for fgtv True

                  ids subsector  ssp_emission
0     1:lvst-lsmm:ch4      lvst     59.862185
1     1:lvst-lsmm:ch4      lsmm      2.511765
2          3:lsmm:n2o      lsmm      6.355724
3          4:agrc:co2      agrc      0.864601
4          5:agrc:ch4      agrc      1.771977
5          6:agrc:n2o      agrc      0.565280
6          7:scoe:co2      scoe      7.702788
7          8:scoe:ch4      scoe      0.033125
8          9:scoe:n2o      scoe      0.058250
9         10:entc:co2      entc           NaN
10        11:entc:ch4      entc           NaN
11        12:entc:n2o      entc           NaN
12        13:fgtv:co2      fgtv           NaN
13        14:fgtv:ch4      fgtv           NaN
14        15:fgtv:n2o      fgtv           NaN
15        16:inen:co2      inen     25.788556
16        17:inen:ch4      inen      0.108583
17        18:inen:n2o      inen      0.191747
18        19:trns:co2      trns      1.791227
19        20:trns:ch4      trns      0.004003
20        21:trns:n2o      trns      0.040425
21        22:ippu:co2      ippu     10.386787
22        23:ippu:ch4      ippu      0.006068
23        24:ippu:n2o      ippu      0.528751
24       50:ippu:hfcs      ippu      0.000000
25  51:ippu:other_fcs      ippu           NaN
26       52:ippu:pfcs      ippu      0.000002
27        53:ippu:sf6      ippu      0.000000
28        54:waso:co2      waso      0.665792
29        55:waso:ch4      waso      7.906004
30        56:waso:n2o      waso      0.012123
31        57:trww:ch4      trww      4.011817
32        58:trww:n2o      trww      2.655611
33        66:ccsq:ch4      ccsq      0.000000
34        67:ccsq:co2      ccsq      0.000000
35        68:ccsq:n2o      ccsq      0.000000
36      69:frst:total      frst     -6.028699
37      70:lndu:total      lndu      6.455362

In [31]:
ssp_emissions_report = dru.group_ssp_emissions_report_vars(ssp_emissions_report)
ssp_emissions_report

                  ids  ssp_emission subsector
0         10:entc:co2      0.000000      entc
1         11:entc:ch4      0.000000      entc
2         12:entc:n2o      0.000000      entc
3         13:fgtv:co2      0.000000      fgtv
4         14:fgtv:ch4      0.000000      fgtv
5         15:fgtv:n2o      0.000000      fgtv
6         16:inen:co2     25.788556      inen
7         17:inen:ch4      0.108583      inen
8         18:inen:n2o      0.191747      inen
9         19:trns:co2      1.791227      trns
10    1:lvst-lsmm:ch4     62.373950      lvst
11        20:trns:ch4      0.004003      trns
12        21:trns:n2o      0.040425      trns
13        22:ippu:co2     10.386787      ippu
14        23:ippu:ch4      0.006068      ippu
15        24:ippu:n2o      0.528751      ippu
16         3:lsmm:n2o      6.355724      lsmm
17         4:agrc:co2      0.864601      agrc
18       50:ippu:hfcs      0.000000      ippu
19  51:ippu:other_fcs      0.000000      ippu
20       52:ippu:pfcs      0.000002      ippu
21        53:ippu:sf6      0.000000      ippu
22        54:waso:co2      0.665792      waso
23        55:waso:ch4      7.906004      waso
24        56:waso:n2o      0.012123      waso
25        57:trww:ch4      4.011817      trww
26        58:trww:n2o      2.655611      trww
27         5:agrc:ch4      1.771977      agrc
28        66:ccsq:ch4      0.000000      ccsq
29        67:ccsq:co2      0.000000      ccsq
30        68:ccsq:n2o      0.000000      ccsq
31      69:frst:total     -6.028699      frst
32         6:agrc:n2o      0.565280      agrc
33      70:lndu:total      6.455362      lndu
34         7:scoe:co2      7.702788      scoe
35         8:scoe:ch4      0.033125      scoe
36         9:scoe:n2o      0.058250      scoe

In [32]:
# check energy subsector
energy_subsectors = ['trns', 'entc', 'fgtv', 'scoe', 'inen', 'ccsq']
ssp_emissions_report[ssp_emissions_report.subsector.isin(energy_subsectors)]

            ids  ssp_emission subsector
0   10:entc:co2      0.000000      entc
1   11:entc:ch4      0.000000      entc
2   12:entc:n2o      0.000000      entc
3   13:fgtv:co2      0.000000      fgtv
4   14:fgtv:ch4      0.000000      fgtv
5   15:fgtv:n2o      0.000000      fgtv
6   16:inen:co2     25.788556      inen
7   17:inen:ch4      0.108583      inen
8   18:inen:n2o      0.191747      inen
9   19:trns:co2      1.791227      trns
11  20:trns:ch4      0.004003      trns
12  21:trns:n2o      0.040425      trns
28  66:ccsq:ch4      0.000000      ccsq
29  67:ccsq:co2      0.000000      ccsq
30  68:ccsq:n2o      0.000000      ccsq
34   7:scoe:co2      7.702788      scoe
35   8:scoe:ch4      0.033125      scoe
36   9:scoe:n2o      0.058250      scoe

In [33]:
model_failed_flag

False

In [34]:
edgar_emissions_groupped = dru.group_ssp_emissions_report_vars(edgar_emissions, emissions_col_name="edgar_emission")
edgar_emissions_groupped["iso_alpha_3"] = dru.iso_alpha_3
edgar_emissions_groupped

              ids  edgar_emission iso_alpha_3
0     10:entc:co2        0.056306         UGA
1     11:entc:ch4        0.003233         UGA
2     12:entc:n2o        0.004118         UGA
3     13:fgtv:co2        0.000000         UGA
4     14:fgtv:ch4        7.845444         UGA
..            ...             ...         ...
57     6:agrc:n2o        8.092843         UGA
58  70:lndu:total       10.611000         UGA
59     7:scoe:co2        0.611469         UGA
60     8:scoe:ch4        2.554441         UGA
61     9:scoe:n2o        0.323356         UGA

[62 rows x 3 columns]

In [35]:
df_report = dru.merge_ssp_with_edgar(ssp_emissions_report, edgar_emissions_groupped)
df_report

,ids,ssp_emission,subsector,edgar_emission,iso_alpha_3,year
0,10:entc:co2,0.000000,entc,0.056306,UGA,2022
1,11:entc:ch4,0.000000,entc,0.003233,UGA,2022
2,12:entc:n2o,0.000000,entc,0.004118,UGA,2022
3,13:fgtv:co2,0.000000,fgtv,0.000000,UGA,2022
4,14:fgtv:ch4,0.000000,fgtv,7.845444,UGA,2022
5,15:fgtv:n2o,0.000000,fgtv,0.093892,UGA,2022
6,16:inen:co2,25.788556,inen,1.282418,UGA,2022
7,17:inen:ch4,0.108583,inen,0.223206,UGA,2022
8,18:inen:n2o,0.191747,inen,0.157472,UGA,2022
9,19:trns:co2,1.791227,trns,3.824464,UGA,2022
10,1:lvst-lsmm:ch4,62.373950,lvst,19.944488,UGA,2022
11,20:trns:ch4,0.004003,trns,0.025259,UGA,2022
12,21:trns:n2o,0.040425,trns,0.053780,UGA,2022
13,22:ippu:co2,10.386787,ippu,1.765612,UGA,2022
14,23:ippu:ch4,0.006068,ippu,0.000000,UGA,2022
15,24:ippu:n2o,0.528751,ippu,0.534607,UGA,2022
16,3:lsmm:n2o,6.355724,lsmm,0.299059,UGA,2022
17,4:agrc:co2,0.864601,agrc,0.000000,UGA,2022
18,50:ippu:hfcs,0.000000,ippu,0.000000,UGA,2022
19,51:ippu:other_fcs,0.000000,ippu,0.000000,UGA,2022
20,52:ippu:pfcs,0.000002,ippu,0.000000,UGA,2022
21,53:ippu:sf6,0.000000,ippu,0.000000,UGA,2022
22,54:waso:co2,0.665792,waso,0.000000,UGA,2022
23,55:waso:ch4,7.906004,waso,0.595829,UGA,2022
24,56:waso:n2o,0.012123,waso,0.000000,UGA,2022
25,57:trww:ch4,4.011817,trww,7.170170,UGA,2022
26,58:trww:n2o,2.655611,trww,0.452025,UGA,2022
27,5:agrc:ch4,1.771977,agrc,0.576887,UGA,2022
28,66:ccsq:ch4,0.000000,ccsq,0.000000,UGA,2022
29,67:ccsq:co2,0.000000,ccsq,0.000000,UGA,2022
30,68:ccsq:n2o,0.000000,ccsq,0.000000,UGA,2022
31,69:frst:total,-6.028699,frst,-10.524000,UGA,2022
32,6:agrc:n2o,0.565280,agrc,8.092843,UGA,2022
33,70:lndu:total,6.455362,lndu,10.611000,UGA,2022
34,7:scoe:co2,7.702788,scoe,0.611469,UGA,2022
35,8:scoe:ch4,0.033125,scoe,2.554441,UGA,2022
36,9:scoe:n2o,0.058250,scoe,0.323356,UGA,2022

In [36]:
dru.group_trns_scoe_inen(df_report)

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year
0,16:inen:co2,inen,26.088885,UGA,1.663096,2022
1,7:scoe:co2,scoe,7.794163,UGA,3.489266,2022
2,19:trns:co2,trns,1.835655,UGA,3.903503,2022
3,10:entc:co2,entc,0.000000,UGA,0.056306,2022
4,11:entc:ch4,entc,0.000000,UGA,0.003233,2022
5,12:entc:n2o,entc,0.000000,UGA,0.004118,2022
6,13:fgtv:co2,fgtv,0.000000,UGA,0.000000,2022
7,14:fgtv:ch4,fgtv,0.000000,UGA,7.845444,2022
8,15:fgtv:n2o,fgtv,0.000000,UGA,0.093892,2022
9,1:lvst-lsmm:ch4,lvst,62.373950,UGA,19.944488,2022
10,22:ippu:co2,ippu,10.386787,UGA,1.765612,2022
11,23:ippu:ch4,ippu,0.006068,UGA,0.000000,2022
12,24:ippu:n2o,ippu,0.528751,UGA,0.534607,2022
13,3:lsmm:n2o,lsmm,6.355724,UGA,0.299059,2022
14,4:agrc:co2,agrc,0.864601,UGA,0.000000,2022
15,50:ippu:hfcs,ippu,0.000000,UGA,0.000000,2022
16,51:ippu:other_fcs,ippu,0.000000,UGA,0.000000,2022
17,52:ippu:pfcs,ippu,0.000002,UGA,0.000000,2022
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022
19,54:waso:co2,waso,0.665792,UGA,0.000000,2022
20,55:waso:ch4,waso,7.906004,UGA,0.595829,2022
21,56:waso:n2o,waso,0.012123,UGA,0.000000,2022
22,57:trww:ch4,trww,4.011817,UGA,7.170170,2022
23,58:trww:n2o,trww,2.655611,UGA,0.452025,2022
24,5:agrc:ch4,agrc,1.771977,UGA,0.576887,2022
25,66:ccsq:ch4,ccsq,0.000000,UGA,0.000000,2022
26,67:ccsq:co2,ccsq,0.000000,UGA,0.000000,2022
27,68:ccsq:n2o,ccsq,0.000000,UGA,0.000000,2022
28,69:frst:total,frst,-6.028699,UGA,-10.524000,2022
29,6:agrc:n2o,agrc,0.565280,UGA,8.092843,2022
30,70:lndu:total,lndu,6.455362,UGA,10.611000,2022

In [37]:
# get duplicated edgar_class
df_report[df_report.duplicated(subset=['ids'], keep=False)]

Empty DataFrame
Columns: [ids, ssp_emission, subsector, edgar_emission, iso_alpha_3, year]
Index: []

In [38]:

reports_dict = dru.run_report_generator(edgar_emissions, ssp_out)

sectoral_emission_report = reports_dict['sectoral_emission_report']
subsector_emission_report = reports_dict['subsector_emission_report']

In [39]:
sectoral_emission_report[sectoral_emission_report['subsector'].isin(energy_subsectors)]

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
0,16:inen:co2,inen,26.088885,UGA,1.663096,2022,1.663097,14.686930,596.619146,1.663097,0.023887,0.979489
1,7:scoe:co2,scoe,7.794163,UGA,3.489266,2022,3.489267,1.233753,18.532123,3.489267,0.050117,1.501689
2,19:trns:co2,trns,1.835655,UGA,3.903503,2022,3.903504,-0.529742,4.276003,3.903504,0.056067,1.589950

In [40]:
sectoral_emission_report

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
0,16:inen:co2,inen,26.088885,UGA,1.663096,2022,1.663097,14.686930,5.966191e+02,1.663097,0.023887,0.979489
1,7:scoe:co2,scoe,7.794163,UGA,3.489266,2022,3.489267,1.233753,1.853212e+01,3.489267,0.050117,1.501689
2,19:trns:co2,trns,1.835655,UGA,3.903503,2022,3.903504,-0.529742,4.276003e+00,3.903504,0.056067,1.589950
9,1:lvst-lsmm:ch4,lvst,62.373950,UGA,19.944488,2022,19.944489,2.127378,1.800259e+03,19.944489,0.286467,3.041876
10,22:ippu:co2,ippu,10.386787,UGA,1.765612,2022,1.765613,4.882823,7.432464e+01,1.765613,0.025360,1.017262
11,23:ippu:ch4,ippu,0.006068,UGA,0.000000,2022,0.000001,6067.313151,3.681229e-05,0.000001,0.000000,0.000000
12,24:ippu:n2o,ippu,0.528751,UGA,0.534607,2022,0.534608,-0.010956,3.430940e-05,0.534608,0.007679,0.428275
13,3:lsmm:n2o,lsmm,6.355724,UGA,0.299059,2022,0.299060,20.252354,3.668318e+01,0.299060,0.004295,0.261640
14,4:agrc:co2,agrc,0.864601,UGA,0.000000,2022,0.000001,864599.899911,7.475330e-01,0.000001,0.000000,0.000000
15,50:ippu:hfcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
16,51:ippu:other_fcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
17,52:ippu:pfcs,ippu,0.000002,UGA,0.000000,2022,0.000001,1.366543,1.867440e-12,0.000001,0.000000,0.000000
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
19,54:waso:co2,waso,0.665792,UGA,0.000000,2022,0.000001,665791.100908,4.432778e-01,0.000001,0.000000,0.000000
20,55:waso:ch4,waso,7.906004,UGA,0.595829,2022,0.595830,12.268898,5.343865e+01,0.595830,0.008558,0.467393
21,56:waso:n2o,waso,0.012123,UGA,0.000000,2022,0.000001,12121.687152,1.469353e-04,0.000001,0.000000,0.000000
22,57:trww:ch4,trww,4.011817,UGA,7.170170,2022,7.170171,-0.440485,9.975199e+00,7.170171,0.102987,2.100490
23,58:trww:n2o,trww,2.655611,UGA,0.452025,2022,0.452026,4.874914,4.855789e+00,0.452026,0.006493,0.372959
24,5:agrc:ch4,agrc,1.771977,UGA,0.576887,2022,0.576888,2.071615,1.428239e+00,0.576888,0.008286,0.455452
28,69:frst:total,frst,-6.028699,UGA,-10.524000,2022,-10.523999,-0.427147,2.020772e+01,10.524001,0.151158,2.444432
29,6:agrc:n2o,agrc,0.565280,UGA,8.092843,2022,8.092844,-0.930151,5.666422e+01,8.092844,0.116239,2.207488
30,70:lndu:total,lndu,6.455362,UGA,10.611000,2022,10.611001,-0.391635,1.726933e+01,10.611001,0.152408,2.451953

In [41]:
sectoral_emission_report.tail(10)

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
19,54:waso:co2,waso,0.665792,UGA,0.000000,2022,0.000001,665791.100908,4.432778e-01,0.000001,0.000000,0.000000
20,55:waso:ch4,waso,7.906004,UGA,0.595829,2022,0.595830,12.268898,5.343865e+01,0.595830,0.008558,0.467393
21,56:waso:n2o,waso,0.012123,UGA,0.000000,2022,0.000001,12121.687152,1.469353e-04,0.000001,0.000000,0.000000
22,57:trww:ch4,trww,4.011817,UGA,7.170170,2022,7.170171,-0.440485,9.975199e+00,7.170171,0.102987,2.100490
23,58:trww:n2o,trww,2.655611,UGA,0.452025,2022,0.452026,4.874914,4.855789e+00,0.452026,0.006493,0.372959
24,5:agrc:ch4,agrc,1.771977,UGA,0.576887,2022,0.576888,2.071615,1.428239e+00,0.576888,0.008286,0.455452
28,69:frst:total,frst,-6.028699,UGA,-10.524000,2022,-10.523999,-0.427147,2.020772e+01,10.524001,0.151158,2.444432
29,6:agrc:n2o,agrc,0.565280,UGA,8.092843,2022,8.092844,-0.930151,5.666422e+01,8.092844,0.116239,2.207488
30,70:lndu:total,lndu,6.455362,UGA,10.611000,2022,10.611001,-0.391635,1.726933e+01,10.611001,0.152408,2.451953

In [42]:
sectoral_emission_report[sectoral_emission_report['subsector'] == 'ippu']

,ids,subsector,ssp_emission,iso_alpha_3,edgar_emission,year,edgar_emission_epsilon,rel_error,squared_diff,direct_weight,norm_weight,log_weight
10,22:ippu:co2,ippu,10.386787,UGA,1.765612,2022,1.765613,4.882823,7.432464e+01,1.765613,0.025360,1.017262
11,23:ippu:ch4,ippu,0.006068,UGA,0.000000,2022,0.000001,6067.313151,3.681229e-05,0.000001,0.000000,0.000000
12,24:ippu:n2o,ippu,0.528751,UGA,0.534607,2022,0.534608,-0.010956,3.430940e-05,0.534608,0.007679,0.428275
15,50:ippu:hfcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
16,51:ippu:other_fcs,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000
17,52:ippu:pfcs,ippu,0.000002,UGA,0.000000,2022,0.000001,1.366543,1.867440e-12,0.000001,0.000000,0.000000
18,53:ippu:sf6,ippu,0.000000,UGA,0.000000,2022,0.000001,-1.000000,1.000000e-12,0.000001,0.000000,0.000000

In [43]:
subsector_emission_report

,subsector,ssp_emission,edgar_emission_epsilon,rel_error,squared_diff,year
0,agrc,3.201858,8.669733,-0.630686,29.897656,2022
1,frst,-6.028699,-10.523999,-0.427147,20.207718,2022
2,inen,26.088885,1.663097,14.686930,596.619146,2022
3,ippu,10.921608,2.300226,3.748059,74.328233,2022
4,lndu,6.455362,10.611001,-0.391635,17.269335,2022
5,lsmm,6.355724,0.299060,20.252354,36.683184,2022
6,lvst,62.373950,19.944489,2.127378,1800.259200,2022
7,scoe,7.794163,3.489267,1.233753,18.532123,2022
8,trns,1.835655,3.903504,-0.529742,4.276003,2022
9,trww,6.667428,7.622196,-0.125262,0.911583,2022
10,waso,8.583919,0.595832,13.406616,63.809537,2022

### Test new error function

In [ ]:
input_df = pd.read_csv('misc/dummy/ssp_output_dummy.csv')
input_df.head()

In [ ]:
dru.run_report_generator(edgar_emissions, input_df)

In [ ]:
df = dru.sectoral_emission_report.copy()
df.head()

In [ ]:
df.to_csv('misc/dummy/sectoral_emission_report_dummy.csv', index=False)

In [ ]:
df.sort_values(by=['norm_weight'], ascending=False, inplace=True)

In [ ]:
df

In [ ]:
df['norm_weight'] * 100

In [ ]:
ef = ErrorFunctions()
ef.calculate_error(error_type='wmape', dataframe=df)

In [ ]:
np.sum(df['norm_weight'] * df['rel_error'].abs()) * 100